# constants.py - Network Constants

# Sequence numbers
SEQUENCE_NUMBER_BITS = 14
MAX_SEQUENCE_HISTORY_LENGTH = 256
SEQ_NUMBER_COUNT = 1 << SEQUENCE_NUMBER_BITS  # 16384
SEQ_NUMBER_HALF = 1 << (SEQUENCE_NUMBER_BITS - 1)  # 8192
SEQ_NUMBER_MASK = SEQ_NUMBER_COUNT - 1  # 0x3FFF

# Packet header
HISTORY_WORD_COUNT_BITS = 4

# Connection limits
MAX_CHANNELS = 16384

# Bunch limits
MIN_BUNCH_HEADER_BITS = 10
MAX_BUNCH_HEADER_BITS = 256
MAX_BUNCH_DATA_BITS = 1024 * 8

MAX_JITTER_CLOCK_TIME_VALUE = 1023
NET_MAX_CONSTRUCTED_PARTIAL_BUNCH_SIZE_BYTES = 1024 * 64

# Sequence history
BITS_PER_WORD = 32
HISTORY_WORDS = MAX_SEQUENCE_HISTORY_LENGTH // BITS_PER_WORD  # 8

# Channel reliable buffer
RELIABLE_BUFFER = 512

# Channel reliable sequence
MAX_CHSEQUENCE = 1024
MAX_CHSEQUENCE_HALF = 512
MAX_CHSEQUENCE_MASK = MAX_CHSEQUENCE - 1 

# Close reason — ValueMax for SerializeInt (== EChannelCloseReason::MAX)
CLOSE_REASON_MAX = 15

# Partial bunch split threshold
MAX_PARTIAL_CHUNK_BYTES = 680

# Handshake
HANDSHAKE_COOKIE_SIZE = 20

# SteelShield
STEELSHIELD_ROLLOVER_COOLDOWN_SECONDS = 2

# FEngineNetworkCustomVersion — EngineNetVer thresholds that affect wire format
ENGINE_NET_VER_CHANNEL_CLOSE_REASON = 7
ENGINE_NET_VER_OPTIONALLY_QUANTIZE_SPAWN_INFO = 13
ENGINE_NET_VER_JITTER_IN_HEADER = 14
ENGINE_NET_VER_SUB_OBJECT_OUTER_CHAIN = 18
ENGINE_NET_VER_MONTAGE_PLAY_INST_ID = 21
ENGINE_NET_VER_SERIALIZE_DOUBLE_VECTORS_AS_DOUBLES = 22
ENGINE_NET_VER_PACKED_VECTOR_LWC_SUPPORT = 23
ENGINE_NET_VER_REP_MOVE_SERVER_FRAME_AND_HANDLE = 25
ENGINE_NET_VER_21_AND_VIEW_PITCH_ONLY_DONOTUSE = 26
ENGINE_NET_VER_SUB_OBJECT_DESTROY_FLAG = 30
ENGINE_NET_VER_DYNAMIC_MONTAGE_SERIALIZATION = 33
ENGINE_NET_VER_PREDICTION_KEY_BASE_NOT_REPLICATED = 34
ENGINE_NET_VER_REP_MOVE_OPTIONAL_ACCELERATION = 35
ENGINE_NET_VER_MONTAGE_PLAY_COUNT_SERIALIZATION = 37
ENGINE_NET_VER_LATEST = 43

# Current target engine version
ENGINE_NET_VER_CURRENT = 43

# FNetworkGUID operator<< serialization format
# UE5 5.3+: uint64 ObjectId via SerializeIntPacked64 (True)
# UE5 <5.3: uint32 Value via operator<< (False)
NET_GUID_PACKED64 = True

# Property replication checksum bit
ENABLE_PROPERTY_CHECKSUMS = True